### ISSUE TITLE
作者好， 我有个第三章依赖注入的小疑问

### ISSUE THREAD

**Issue by tetratensor** [jiangjinnan/InsideAspNetCore3#1]
第三章依赖注入Cat.cs文件中GetService方法中

为什么返回IEnumerable<T>类型的和普通类型的如果没有注册的处理情况不一样， 一个是返回空数组，一个时返回null？
`
if (!_registries.TryGetValue(elementType, out registry))
                {
                    return Array.CreateInstance(elementType, 0);
                }
`

如果返回某个类型的
`

            //Normal
            return _registries.TryGetValue(serviceType, out registry)
                    ? GetServiceCore(registry, new Type[0])
                    : null;
`

**Comment by itzxpeng** [comment]
书上第84页第二段，也许可以回答你的问题

**Comment by jiangjinnan** [comment]
这是API定义的一个推荐做法，如果一个方法或者属性返回一个集合，我们不推荐返回Null，而是返回一个空的集合。判断集合元素是否存在最好通过集合是否为空来判断，而不是通过是否为Null来判断。
